# install basic packages

- name: install basic packages
  shell: "cd /usr/nekoware ; ./nekodeps.pl {{ item }} ; ./install.sh"
  become: true
  ignore_errors: yes
  register: nekodeps_output
  with_items:
    - mtr
    - bash
    - vim
    - less
    - unzip

- name: nekodeps results
  debug:
    msg: "{{ nekodeps_output }}"
