- name: install findutils
  shell: "cd /usr/nekoware ; ./nekodeps.pl findutils ; ./install.sh"
  become: true
  ignore_errors: yes
  register: findutils_output

- name: findutils results
  debug:
    msg: "{{ findutils_output }}"

- name: set up cron entry for updatedb
  cron:
    name: "run updatedb"
    minute: 0
    hour: 3
    user: root
    job: "/usr/nekoware/bin/updatedb --prunepaths='/dev /hw /CDROM /mnt /tmp /usr2/MIPS /usr2/GCC /stand' > /dev/null 2>&1"
